---
title: "Ceap Report [p. 2]"
author: "Italo Batista"
date: "September 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Perguntas
### 1. Quais os tipos de despesas com os deputados que, no total, foram maiores do que o investimento com o Museu Nacional?
### 2. Quais as datas (mes/ano) em que os deputados mais gastaram? Qual foi o tipo de despesa mais consumida?

## Importando dados

```{r message=FALSE, warning=FALSE, error=FALSE}
require(readr)
require(here)
data.ceap = read_csv(here::here("predictive_data_science/data/ceap.csv"))
investiment.mn <- read_delim(here::here("predictive_data_science/data/investimento-mn.csv"), delim="\t", escape_double = FALSE, trim_ws = TRUE)
```

## Quais os tipos de despesas com os deputados que, no total, foram maiores do que o investimento com o Museu Nacional?

```{r message=FALSE, warning=FALSE, error=FALSE}
require(lubridate)
require(tidyverse)

data.ceap.by.year = data.ceap %>%
  mutate(year = year(dataEmissao)) %>%
  group_by(year, tipoDespesa) %>%
  summarise(totalExpenditure = sum(valorLíquido)) %>%
  ungroup() %>%
  mutate(year = as.numeric(year)) %>%
  na.omit()
```

```{r message=FALSE, warning=FALSE, error=FALSE}
require(tidyverse)
require(scales)

max.year = max(data.ceap.by.year$year)
min.year = min(data.ceap.by.year$year)

investiment.mn.filter.year = investiment.mn %>%
  filter( year <= max.year & year >= min.year)

data.ceap.by.year %>%
  ggplot() +
  geom_point(aes(x=year, y=totalExpenditure), alpha=0.3) + 
  geom_line(aes(x=year, y=totalExpenditure, group=tipoDespesa), linetype = 2, size=0.3) +
  geom_line(data=investiment.mn.filter.year, aes(x=year, y=investiment), color="red") +
  scale_x_continuous(breaks=c(min.year:max.year))

```

```{r message=FALSE, warning=FALSE, error=FALSE}
investiment.mn %>%
  ggplot(aes(x=year, y=investiment), fill="deepink") +
  geom_point() + 
  geom_line(linetype = 2) +
  scale_x_continuous(breaks = c(2001:2018))
```

```{r message=FALSE, warning=FALSE, error=FALSE}

```

```{r message=FALSE, warning=FALSE, error=FALSE}

```

```{r message=FALSE, warning=FALSE, error=FALSE}

```