---
title: "eda-gastos-ceao"
author: "Italo Batista"
date: "29 de agosto de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(readr)
library(here)
data.ceap = read_csv(here::here("predictive_data_science/data/ceap.csv"))
limit.ceap = read_csv(here::here("predictive_data_science/data/limiteMensalCEAP.csv"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)

# não sei se é necessário
# dados.ceap$t <- as.numeric(sub(",", ".", dados.ceap$valorGlosa, fixed = TRUE)) 
data.ceap = data.ceap %>%
  mutate(valorGlosa = str_replace_all(valorGlosa,"[[:punct:]]", ".")) %>%
  mutate(valorGlosa = as.numeric(valorGlosa)) 
```

# Explorando dados

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
summary(data.ceap)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
require(gridExtra)

segment.y = 5000
x.init = min(data.ceap %>% select(valorLíquido))
x.end = max(data.ceap %>% select(valorLíquido))
x.3rd.qrtl = 513
  
histogram = data.ceap %>%
  ggplot() +
  geom_histogram(aes(valorLíquido)) +
  theme(axis.text.x = element_text(size=8),
        axis.title.x = element_text(size=10),
        axis.text.y = element_text(size=8),
        axis.title.y = element_text(size=10),
        plot.title = element_text(hjust = 0.1, size=10))

plot1 = histogram +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE))

  plot2 = histogram +
  scale_x_continuous(limits = c(x.init, x.3rd.qrtl)) +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  ggtitle("Sem valores extremos superiores")

plot3 = histogram +
  scale_x_continuous(limits = c(x.init, x.end)) +
  scale_y_continuous(trans='log2',
                     labels = function(x) format(x, scientific = FALSE)) +
  ggtitle("Escala logarítmica")

plot4 = histogram +
  scale_x_continuous(limits = c(x.init, x.3rd.qrtl)) +
  scale_y_continuous(trans='log2',
                     labels = function(x) format(x, scientific = FALSE)) +
  ggtitle("Escala logarítmica e sem valores extremos superiores")

grid.arrange(plot1, plot2, plot3, plot4, ncol=2)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
# Quanto cada deputado gastou cada mês
library(lubridate)

data.ceap.month = data.ceap %>%
  mutate(month = month(dataEmissao),
         year = year(dataEmissao)) %>%
  group_by(month, year, nomeParlamentar, sgUF) %>%
  summarise(totalExpenditureMonth = sum(valorLíquido)) %>%
  ungroup()
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
# Adicionar limite menal
data.ceap.month  = left_join(data.ceap.month, limit.ceap, by=c("sgUF"="UF"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

```

# Perguntas

## 1. Quais são os deputados que gastaram mais dinheiro da CEAP? Quais são os mais econômicos? (7,5 pts)

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
ranking.expenditures = data.ceap %>%
  filter(valorLíquido > 0) %>%
  group_by(nomeParlamentar) %>%
  summarise(gastoTotal = sum(valorLíquido)) %>%
  ungroup() %>%
  arrange(gastoTotal)

top.spenders = ranking.expenditures %>%
  top_n(10) %>%
  mutate(expenses_gat = "Spender")

top.economicals = ranking.expenditures %>%
  top_n(-10) %>%
  mutate(expenses_gat = "Economical")

ranking.expenditures = rbind(top.spenders, top.economicals)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
expense.min = min(ranking.expenditures$gastoTotal)
expense.max = max(ranking.expenditures$gastoTotal)

m_breaks = ranking.expenditures %>% select(gastoTotal) %>% distinct()

ranking.expenditures %>%
  mutate(nomeParlamentar = reorder(nomeParlamentar, gastoTotal)) %>%
  
  ggplot(aes(nomeParlamentar, gastoTotal, fill=expenses_gat, color=expenses_gat)) +
  geom_bar(stat = "identity") +
  geom_text(data = top.economicals, size=2.8, color="#FF6600", hjust=1.1, fontface="bold", aes(label=gastoTotal)) +
  geom_text(data = top.spenders, size=2.8, color="white", hjust=1.1, fontface="bold", aes(label=gastoTotal)) +
  coord_flip() +
  
  scale_y_continuous(limits = c(expense.min - 100000, expense.max)) +
  scale_fill_manual(labels = c("10+ Econômicos", "10+ Gastadores"), values=c("#FF6600", "#4F0C68")) +
  scale_color_manual(labels = c("10+ Econômicos", "10+ Gastadores"), values=c("#FF6600", "#4F0C68")) +
  
  labs(title="Deputados que mais e menos gastam o auxílio da CEAP", 
       x ="Gasto total", 
       y = "Nome do Parlamentar") +
  theme(plot.title = element_text(hjust = -1.5),
        legend.title = element_blank(), legend.position = "top")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
summary(ranking.expenses)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

```

# qual a data mes/ano em que os deputados mais gastaram?