---
title: "Polygraph's Film Dialogue Analyzis"
output:
  html_document:
    fig_width: 6
    fig_height: 4
    theme: journal
theme: united
highlight: tango
css: styles.css
---

```{r warning=FALSE, error=FALSE, message=FALSE}
library(tidyverse, warn.conflicts = F)
```
```{r warning=FALSE, error=FALSE, message=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(readr)
```
```{r warning=FALSE, error=FALSE, message=FALSE}
library(rvest)
library(plotly)
library(cluster)
library(ggdendro)
library(ggfortify)
library(broom)
#theme_set(theme_light())
theme_set(theme_bw())
```

```{r warning=FALSE, message=FALSE, error=FALSE}
characters = read_csv("data/character_list5.csv")
big_data = read_csv("data/meta_data7.csv") %>% na.omit()
```

```{r warning=FALSE, error=FALSE, message=FALSE}
data_golden_age = big_data %>% filter(year <= 1970) 
characters_golde_age = characters %>% filter(script_id %in% data_golden_age$script_id) %>% select(-c(age))
```

Calculando número de personagns homens e mulheres.

```{r warning=FALSE, error=FALSE, message=FALSE}
gendersf = characters_golde_age %>%
  filter(gender == 'f') %>%
  group_by(script_id) %>%
  summarise(nf = n())

gendersm = characters_golde_age %>%
  filter(gender == 'm') %>%
  group_by(script_id) %>%
  summarise(nm = n())

genders = full_join(gendersm, gendersf, by="script_id")
```

Calculando soma de número médio de palavras por minuto por gênero

```{r warning=FALSE, error=FALSE, message=FALSE}
wordsf = characters_golde_age %>%
  filter(gender == 'f') %>%
  group_by(script_id) %>%
  summarise(wordsf = sum(words))

wordsm = characters_golde_age %>%
  filter(gender == 'm') %>%
  group_by(script_id) %>%
  summarise(wordsm = sum(words))

words = full_join(wordsf, wordsm, by="script_id")
```

```{r warning=FALSE, error=FALSE, message=FALSE}
d = data_golden_age
d = left_join(d, genders, by="script_id")
d = left_join(d, words, by="script_id")
```

# filmes:
#   tamanho do elenco
#   proporção de homens ou mulheres
#   bilheteria
#   quantidade de palavras no filme (se um filme é mais contemplativo ou tem mais diálogos)


