---
title: "Untitled"
author: "Italo"
date: "3 de janeiro de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(tidytext)
library(tm) # para stopwords
```

```{r message=FALSE, error=FALSE, warning=FALSE}
hh_poetry = read_delim("data/hilda_hilst_poetry.csv", "\t", escape_double = FALSE, trim_ws = TRUE)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
books = hh_poetry %>%
  group_by(LIVRO) %>%
  summarise(
    QNT_POEMAS = n(),
    QNT_VERSOS = sum(QNT_VERSOS),
    TAM = sum(TAM_POEMA)
  )
```

# TRIGRAMS

```{r message=FALSE, error=FALSE, warning=FALSE}
hh_bigrams = hh_poetry %>%
    unnest_tokens(bigram, POEMA, token = "ngrams", n = 2)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
pronouns = c("ele", "eles", "ela", "elas", "eu", "tu", "sou", "és", "deus", "deusa", "me", "te")
stopwords = stopwords("portuguese")

bigram_counts <- hh_bigrams %>%
  count(bigram, sort = TRUE) %>%
  separate(bigram, c("pronoun", "around"), sep = " ") %>%
  filter((pronoun %in% pronouns & ! around %in% stopwords))

bigram_counts = hh_bigrams %>%
  count(bigram, sort = TRUE) %>%
  separate(bigram, c("around", "pronoun"), sep = " ") %>%
  filter((pronoun %in% pronouns & ! around %in% stopwords)) %>%
  rbind(bigram_counts)

pronouns_fem = c("ela", "elas", "eu", "sou", "deusa", "te")
pronouns_masc = c("ele", "eles", "tu", "és", "deus", "me")

bigram_counts$pronoun[bigram_counts$pronoun %in% pronouns_masc] = "masc"
bigram_counts$pronoun[bigram_counts$pronoun %in% pronouns_fem] = "fem"

bigram_counts = bigram_counts %>%
  count(pronoun, around, wt = n, sort = TRUE) %>%
  rename(total = nn)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
word_ratios <- bigram_counts %>%
    group_by(around) %>%
    filter(sum(total) > 2) %>%
    ungroup() %>%
    spread(pronoun, total, fill = 0) %>%
    mutate_if(is.numeric, funs((. + 1) / sum(. + 1))) %>%
    mutate(logratio = log2(fem / masc)) %>%
    arrange(desc(logratio)) 
```

```{r message=FALSE, error=FALSE, warning=FALSE}
word_ratios %>%
    mutate(abslogratio = abs(logratio)) %>%
    group_by(logratio < 0) %>%
    top_n(15, abslogratio) %>%
    ungroup() %>%
    mutate(word = reorder(around, logratio)) %>%
    ggplot(aes(word, logratio, color = logratio < 0)) +
    geom_segment(aes(x = word, xend = word,
                     y = 0, yend = logratio), 
                 size = 1.1, alpha = 0.6) +
    geom_point(size = 3.5) +
    coord_flip() +
    labs(x = NULL, 
         y = "Quantidade de vezes que uma dada palavra aparece ao redor de \nsujeitos femininos em comparação com sujeitos masculinos",
         title = "Palavras ao redor de sujeitos masculinos e femininos \nna obra poética de Hilda Hilst") +
    scale_color_discrete(name = "", labels = c("Sujeitos femininos", "Sujeitos masculinos")) +
    scale_y_continuous(breaks = seq(-3, 3),
                       labels = c("0.125x", "0.25x", "0.5x", 
                                  "Same", "2x", "4x", "8x"))
```

# Analise de sentimento

```{r message=FALSE, error=FALSE, warning=FALSE}
lexico = read_csv("data/lexicos/oplexicon_v3.0/lexico_v3.0.csv")
```

Reproduzindo jane austen

```{r message=FALSE, error=FALSE, warning=FALSE}
library(janeaustenr)
library(dplyr)
library(stringr)

tidy_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]", 
                                                 ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
nrcjoy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

tidy_books %>%
  filter(book == "Emma") %>%
  inner_join(nrcjoy) %>%
  count(word, sort = TRUE)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
janeaustensentiment <- tidy_books %>%
  inner_join(get_sentiments("bing")) %>%
  count(book, index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
ggplot(janeaustensentiment, aes(index, sentiment, fill = book)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~book, ncol = 2, scales = "free_x")
```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r}
hh_tidy_books <- hh_poetry %>%
  unnest_tokens(palavra, POEMA) %>%
  group_by(LIVRO) %>%
  mutate(palavra_index = row_number()) %>%
  ungroup()
```

```{r message=FALSE, error=FALSE, warning=FALSE}
positive_words <- lexico %>% 
  filter(score == 1) %>%
  mutate(palavra = simbolo) %>%
  select(palavra)

hh_tidy_books %>%
  inner_join(positive_words) %>%
  count(palavra, sort = TRUE)
```

```{r message=FALSE, error=FALSE, warning=FALSE}
hh_sentiment <- hh_tidy_books %>%
  inner_join( lexico %>% mutate(palavra = simbolo) ) %>%
  count(LIVRO, index = palavra_index %/% 80, score) %>%
  spread(score, n, fill = 0) 

colnames(hh_sentiment)[3] <- "negative"
colnames(hh_sentiment)[4] <- "neutro"
colnames(hh_sentiment)[5] <- "positive"

hh_sentiment = hh_sentiment %>%
  mutate(sentiment = positive - negative) %>%
  select(c(LIVRO, index, sentiment))
```

```{r message=FALSE, error=FALSE, warning=FALSE, fig.height=20}
ggplot(hh_sentiment, aes(index, sentiment, fill = LIVRO)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~LIVRO, ncol = 4, scales = "free_x")
```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```

```{r message=FALSE, error=FALSE, warning=FALSE}

```


## Most common positive and negative words
## sentimneto atraves dos livros

